### ISSUE TITLE
Consider not persisting validators in the client

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodePackage-lighthouse-prater#18]
Currently, there is not implemented a way to delete validators using the Lighthouse client API. Consider not persisiting the validators in the docker volume, so it fetches from the web3signer every single time

**Comment by mgarciate** [comment]
You're right. We can just disable validators on the fly via 
```
PATCH /lighthouse/validators/{{pubkey}}
{
    "enabled": false
}
```

**Comment by pablomendezroyo** [comment]
done

**Comment by pablomendezroyo** [comment]
done
