### ISSUE TITLE
Mismatch between URL link and Version under the "Version" information in the DAppStore Installer page

### ISSUE THREAD

**Issue by sushilman** [dappnode/DAppNodePackage-lighthouse-prater#44]
The issue here is similar to: 
https://github.com/dappnode/DAppNodePackage-Teku-Prater/issues/58

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**DAppNode version:**

- Package version: 
- OS: 
- Browser 

**Additional context**

**Comment by pablomendezroyo** [comment]
Most of the times issues come from the upstream github project (Lighthouse in this case) and not from our repository, thats why we redirect users to the upstream and not to ours
