### ISSUE TITLE
Lighthouse Prater v0.1.2 not working

### ISSUE THREAD

**Issue by mgarciate** [dappnode/DAppNodePackage-lighthouse-prater#49]
**Describe the bug**

Lighthouse Prater not working

**To Reproduce**

1. Install the package
2. Check logs

**Expected behavior**

Lighthouse should be synced after a while

**Screenshots**

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/7695193/172016708-838dd5dd-cb33-4cb5-8323-45e8a072ea0e.png">

**DAppNode version:**

- Package version: 0.1.2 (v2.3.0 upstream)
- core.dnp.dappnode.eth: 0.2.55
- dappmanager.dnp.dappnode.eth: 0.2.50, commit: 552ab6c8

**Comment by pablomendezroyo** [comment]
which was the web3signer version you were using when experiencing this issue?

It should be >= 0.1.6

**Comment by mgarciate** [comment]
Version: 0.1.6 (22.5.1 upstream)

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DAppNodePackage-lighthouse-prater/pull/50
