### ISSUE TITLE
Test Lighthouse + web3signer in network prater

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodePackage-lighthouse-prater#51]
**Test instructions**

You must have at least 2 Prater validators.

Install the [web3signer prater](https://github.com/dappnode/DAppNodePackage-web3signer-prater) and the client [Lighthouse](https://github.com/dappnode/DAppNodePackage-lighthouse-prater). You must get the hash from the Github latest release "dot".

In the client use the checkpoint sync feature to be able to start validating in minutes.

The web3signer will listen only to one client, you must select the client Lighthouse at config.

For a deeper test, you may find it useful to check out the grafana dashboards from the client, web3signer, and docker host.

**Test report**

With an editable unique comment report any errors and feedback you may find necessary.

**Testers**
- @pablomendezroyo :heavy_check_mark: 
- @3alpha 
- @tropicar :heavy_check_mark: 
- @mgarciate :heavy_check_mark:

**Comment by pablomendezroyo** [comment]
worked on my side :heavy_check_mark:

**Comment by tropicar** [comment]
Works from my side :heavy_check_mark:
